### ISSUE TITLE
Registration?

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/ZarrDatasets.jl#3]
Its amazing to have this package, thanks @Alexander-Barth 

We are keen to use it as a Zarr backend in Rasters.jl:
https://github.com/rafaqz/Rasters.jl/pull/640

Are there any blockers to registration currently, or anything we can help with?

**Comment by Alexander-Barth** [comment]
Thanks for the nice words. Yes I register this package!
(I wanted to fix some Aqua issues before, but it is now done)
